// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcommerceProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241030093043_AddPermissionsAndUserPermissionnn")]
    partial class AddPermissionsAndUserPermissionnn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApplicationUserModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "bc2ad2c5-7532-40e3-9af8-f19fb8e3f612",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e23d1a45-fc62-45d8-842a-ab25a1b58047",
                            CreatedAt = new DateTime(2024, 10, 30, 9, 30, 42, 769, DateTimeKind.Utc).AddTicks(5582),
                            Email = "admin@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEDNSX6o8n4LasUdtYw/pSU4Dj6WzL53kEBTrw0JWUg2BepsQxRg/UhCCTV52jI9FaQ==",
                            PhoneNumberConfirmed = false,
                            RoleId = "B993F718-51B6-4FBE-9F17-037FA1585827",
                            SecurityStamp = "87283a0e-49a5-45a1-b99b-9f7788384ba5",
                            Slug = "admin-user",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2024, 10, 30, 9, 30, 42, 769, DateTimeKind.Utc).AddTicks(5589),
                            UserName = "adminUser"
                        });
                });

            modelBuilder.Entity("EcommerceProject.Areas.Admin.Models.CustomRoleModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "B993F718-51B6-4FBE-9F17-037FA1585827",
                            CreatedAt = new DateTime(2024, 10, 30, 9, 30, 42, 708, DateTimeKind.Utc).AddTicks(9282),
                            Name = "Admin",
                            Slug = "admin",
                            UpdatedAt = new DateTime(2024, 10, 30, 9, 30, 42, 708, DateTimeKind.Utc).AddTicks(9283)
                        },
                        new
                        {
                            Id = "C0CF4D0F-9BC6-4B70-BAED-2CA10F1AAA30",
                            CreatedAt = new DateTime(2024, 10, 30, 9, 30, 42, 708, DateTimeKind.Utc).AddTicks(9287),
                            Name = "Subadmin",
                            Slug = "subadmin",
                            UpdatedAt = new DateTime(2024, 10, 30, 9, 30, 42, 708, DateTimeKind.Utc).AddTicks(9287)
                        },
                        new
                        {
                            Id = "5482176B-6706-476D-A273-1EA9AD5AD217",
                            CreatedAt = new DateTime(2024, 10, 30, 9, 30, 42, 708, DateTimeKind.Utc).AddTicks(9292),
                            Name = "Supersubadmin",
                            Slug = "supersubadmin",
                            UpdatedAt = new DateTime(2024, 10, 30, 9, 30, 42, 708, DateTimeKind.Utc).AddTicks(9292)
                        });
                });

            modelBuilder.Entity("EcommerceProject.Areas.Admin.Models.OtpModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Otp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Otps");
                });

            modelBuilder.Entity("EcommerceProject.Areas.Admin.Models.PermissionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 10, 30, 9, 30, 42, 769, DateTimeKind.Utc).AddTicks(5711),
                            PermissionName = "Create Product",
                            UpdatedAt = new DateTime(2024, 10, 30, 9, 30, 42, 769, DateTimeKind.Utc).AddTicks(5711)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 10, 30, 9, 30, 42, 769, DateTimeKind.Utc).AddTicks(5717),
                            PermissionName = "Edit Product",
                            UpdatedAt = new DateTime(2024, 10, 30, 9, 30, 42, 769, DateTimeKind.Utc).AddTicks(5718)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 10, 30, 9, 30, 42, 769, DateTimeKind.Utc).AddTicks(5719),
                            PermissionName = "Delete Product",
                            UpdatedAt = new DateTime(2024, 10, 30, 9, 30, 42, 769, DateTimeKind.Utc).AddTicks(5719)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 10, 30, 9, 30, 42, 769, DateTimeKind.Utc).AddTicks(5720),
                            PermissionName = "View Orders",
                            UpdatedAt = new DateTime(2024, 10, 30, 9, 30, 42, 769, DateTimeKind.Utc).AddTicks(5720)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 10, 30, 9, 30, 42, 769, DateTimeKind.Utc).AddTicks(5721),
                            PermissionName = "Manage Users",
                            UpdatedAt = new DateTime(2024, 10, 30, 9, 30, 42, 769, DateTimeKind.Utc).AddTicks(5721)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 10, 30, 9, 30, 42, 769, DateTimeKind.Utc).AddTicks(5737),
                            PermissionName = "Access Admin Dashboard",
                            UpdatedAt = new DateTime(2024, 10, 30, 9, 30, 42, 769, DateTimeKind.Utc).AddTicks(5737)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 10, 30, 9, 30, 42, 769, DateTimeKind.Utc).AddTicks(5738),
                            PermissionName = "Edit User",
                            UpdatedAt = new DateTime(2024, 10, 30, 9, 30, 42, 769, DateTimeKind.Utc).AddTicks(5738)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 10, 30, 9, 30, 42, 769, DateTimeKind.Utc).AddTicks(5739),
                            PermissionName = "Delete User",
                            UpdatedAt = new DateTime(2024, 10, 30, 9, 30, 42, 769, DateTimeKind.Utc).AddTicks(5739)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 10, 30, 9, 30, 42, 769, DateTimeKind.Utc).AddTicks(5740),
                            PermissionName = "Create Category",
                            UpdatedAt = new DateTime(2024, 10, 30, 9, 30, 42, 769, DateTimeKind.Utc).AddTicks(5741)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 10, 30, 9, 30, 42, 769, DateTimeKind.Utc).AddTicks(5742),
                            PermissionName = "Edit Category",
                            UpdatedAt = new DateTime(2024, 10, 30, 9, 30, 42, 769, DateTimeKind.Utc).AddTicks(5743)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 10, 30, 9, 30, 42, 769, DateTimeKind.Utc).AddTicks(5743),
                            PermissionName = "Delete Category",
                            UpdatedAt = new DateTime(2024, 10, 30, 9, 30, 42, 769, DateTimeKind.Utc).AddTicks(5744)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 10, 30, 9, 30, 42, 769, DateTimeKind.Utc).AddTicks(5745),
                            PermissionName = "Create Subcategory",
                            UpdatedAt = new DateTime(2024, 10, 30, 9, 30, 42, 769, DateTimeKind.Utc).AddTicks(5745)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 10, 30, 9, 30, 42, 769, DateTimeKind.Utc).AddTicks(5746),
                            PermissionName = "Edit Subcategory",
                            UpdatedAt = new DateTime(2024, 10, 30, 9, 30, 42, 769, DateTimeKind.Utc).AddTicks(5746)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 10, 30, 9, 30, 42, 769, DateTimeKind.Utc).AddTicks(5747),
                            PermissionName = "Delete Subcategory",
                            UpdatedAt = new DateTime(2024, 10, 30, 9, 30, 42, 769, DateTimeKind.Utc).AddTicks(5747)
                        });
                });

            modelBuilder.Entity("EcommerceProject.Areas.Admin.Models.UserPermissionModel", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(0);

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("UserId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("UserPermissions");

                    b.HasData(
                        new
                        {
                            UserId = "bc2ad2c5-7532-40e3-9af8-f19fb8e3f612",
                            PermissionId = 1
                        },
                        new
                        {
                            UserId = "bc2ad2c5-7532-40e3-9af8-f19fb8e3f612",
                            PermissionId = 2
                        },
                        new
                        {
                            UserId = "bc2ad2c5-7532-40e3-9af8-f19fb8e3f612",
                            PermissionId = 3
                        },
                        new
                        {
                            UserId = "bc2ad2c5-7532-40e3-9af8-f19fb8e3f612",
                            PermissionId = 4
                        },
                        new
                        {
                            UserId = "bc2ad2c5-7532-40e3-9af8-f19fb8e3f612",
                            PermissionId = 5
                        },
                        new
                        {
                            UserId = "bc2ad2c5-7532-40e3-9af8-f19fb8e3f612",
                            PermissionId = 6
                        },
                        new
                        {
                            UserId = "bc2ad2c5-7532-40e3-9af8-f19fb8e3f612",
                            PermissionId = 7
                        },
                        new
                        {
                            UserId = "bc2ad2c5-7532-40e3-9af8-f19fb8e3f612",
                            PermissionId = 8
                        },
                        new
                        {
                            UserId = "bc2ad2c5-7532-40e3-9af8-f19fb8e3f612",
                            PermissionId = 9
                        },
                        new
                        {
                            UserId = "bc2ad2c5-7532-40e3-9af8-f19fb8e3f612",
                            PermissionId = 10
                        },
                        new
                        {
                            UserId = "bc2ad2c5-7532-40e3-9af8-f19fb8e3f612",
                            PermissionId = 11
                        },
                        new
                        {
                            UserId = "bc2ad2c5-7532-40e3-9af8-f19fb8e3f612",
                            PermissionId = 12
                        },
                        new
                        {
                            UserId = "bc2ad2c5-7532-40e3-9af8-f19fb8e3f612",
                            PermissionId = 13
                        },
                        new
                        {
                            UserId = "bc2ad2c5-7532-40e3-9af8-f19fb8e3f612",
                            PermissionId = 14
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ApplicationUserModel", b =>
                {
                    b.HasOne("EcommerceProject.Areas.Admin.Models.CustomRoleModel", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EcommerceProject.Areas.Admin.Models.UserPermissionModel", b =>
                {
                    b.HasOne("EcommerceProject.Areas.Admin.Models.PermissionModel", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationUserModel", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("EcommerceProject.Areas.Admin.Models.CustomRoleModel", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ApplicationUserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ApplicationUserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("EcommerceProject.Areas.Admin.Models.CustomRoleModel", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationUserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ApplicationUserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApplicationUserModel", b =>
                {
                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("EcommerceProject.Areas.Admin.Models.PermissionModel", b =>
                {
                    b.Navigation("UserPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
